apiVersion: v1
kind: Pod
spec:
  containers:
  - name: go
    image: golang:latest
    command:
    - sleep
    args:
    - infinity
  - name: rust
    image: rust:latest
    command:
    - sleep
    args:
    - infinity
